### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by zapplebee** [craiga/will-of-the-prophets#120]
I successfully installed the app inside of a Docker container but am receiving 500 errors at all of the endpoints. Is there additional environmental configuration that is not documented in the readme?

**Comment by craiga** [comment]
Hey, thanks for taking a look! Looks like there's a few things going on here.

It looks like you're getting these errors because the database schema doesn't exist. By default, the site will use a `db.sqlite3` file for its database locally, which isn't shared across Docker containers.

FWIW, I should point out that the recommended way to get this site running locally is to use [pipenv](https://pipenv.readthedocs.io/en/latest/). I'm hesitant to add Docker to this repo as the site and its deployment are very simple and I'd like to keep it that way.

Having said that, you should be able to use Docker if you want, so consider this documentation of what you need to do in order to get things working.

Here's the `Dockerfile` and `docker-compose.yml` I used to get the site working:

```Dockerfile
FROM python:3

ENV PYTHONUNBUFFERED=1

# Install Dockerize, which will let us wait for Postgres before starting Django.
# https://github.com/jwilder/dockerize
RUN apt-get update && apt-get install -y wget
ENV DOCKERIZE_VERSION v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

RUN mkdir /var/will-of-the-prophets
WORKDIR /var/will-of-the-prophets

RUN pip install pipenv
ADD Pipfile /var/will-of-the-prophets/
ADD Pipfile.lock /var/will-of-the-prophets/
RUN pipenv install --deploy --system

ADD . /var/will-of-the-prophets
CMD gunicorn will_of_the_prophets.wsgi:application --bind 0.0.0.0:8000 --workers 1
```

```YAML
version: '3'
services:

  db:
    image: postgres
    environment:
      POSTGRES_DB: will-of-the-prophets
      POSTGRES_USER: will-of-the-prophets
      POSTGRES_PASSWORD: security-is-important

  web:
    build: .
    command: dockerize -wait tcp://db:5432 python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    environment:
      DEBUG: 1
      SECRET_KEY: security-is-important
      DATABASE_URL: postgresql://will-of-the-prophets:security-is-important@db:5432/will-of-the-prophets
      DJANGO_SETTINGS_MODULE: will_of_the_prophets.settings.docker
    depends_on:
      - db
```

Because we're using [django_heroku](https://github.com/heroku/django-heroku), we need to workaround [an issue where an SSL connection to the database is being forced on us](https://github.com/heroku/django-heroku/issues/10) by overriding some settings. The following needs to go into `will_of_the_prophets/settings/docker.py`:

```python
"""
Settings for running in Docker.

Workaround for https://github.com/heroku/django-heroku/issues/10
"""

import dj_database_url

from will_of_the_prophets.settings import *


DATABASES["default"] = dj_database_url.config(ssl_require=False)
```

You'll also need to create the database and load fixtures with the following commands:

```
docker-compose run --rm web python manage.py migrate
docker-compose run --rm web python manage.py loaddata buttholes special_squares rolls
```
